<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>co.analisys</groupId>
	<artifactId>gimnasio-microservicios</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>
	<name>gimnasio-microservicios</name>
	<description>Aggregator - Sistema de Gestión de un Gimnasio (arquitectura de microservicios)</description>

	<modules>
		<module>services/miembro-microservice</module>
		<module>services/entrenador-microservice</module>
		<module>services/clase-microservice</module>
		<module>services/equipo-microservice</module>
	</modules>
</project>
