server.port = 8080

entrenador.service.url=${ENTRENADOR_SERVICE_URL:http://localhost:8081}
miembro.service.url=${MIEMBRO_SERVICE_URL:http://localhost:8083}
equipo.service.url=${EQUIPO_SERVICE_URL:http://localhost:8082}
clase.service.url=${CLASE_SERVICE_URL:http://localhost:8084}|