server.port = 8080

entrenador.service.url=${ENTRENADOR_SERVICE_URL:http://localhost:8081}
miembro.service.url=${MIEMBRO_SERVICE_URL:http://localhost:8083}
equipo.service.url=${EQUIPO_SERVICE_URL:http://localhost:8082}
clase.service.url=${CLASE_SERVICE_URL:http://localhost:8084}
pago.service.url=${PAGO_SERVICE_URL:http://localhost:8086}
monitoreo.service.url=${MONITOREO_SERVICE_URL:http://localhost:8087}

# Keycloak JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/gimnasio}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/gimnasio/protocol/openid-connect/certs}

# Swagger/OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs